### ISSUE TITLE
Combining Hoppers into one Branch

### ISSUE THREAD

**Issue by KyroVibe** [Team997Coders/2018BunnyBot#13]
Combine the front hopper subsystem and back hopper subsystem into on branch

**Comment by RohanPankaj** [comment]
They should be in the "Hooper" branch although I still need to go back and fix some of my errors. Will try to do that tonight.

**Comment by RohanPankaj** [comment]
Yes me and Conner resolved the issues and you should be able to see both the front and back hopper code in the "Hopper" branch
